feat(01-building-blocks): Adding failed step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -12,4 +12,12 @@ jobs: # This is what jobs are included in our workflow
             - name: Say Hello
               run: echo "Hello, World!"
     echo-goodbye: 
+        runs-on: ubuntu-latest
+        steps:
+            - name: Failed step
+              run: | # The pipe is required for multiple lines
+                echo "I will fail"
+                exit 1
+            - name: Say Goodbye
+              run: echo "Goodbye!"
 
